// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"
	"io"

	"github.com/google/uuid"
	"github.com/stpnv0/WarehouseControl/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockauditService creates a new instance of mockauditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauditService {
	mock := &mockauditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauditService is an autogenerated mock type for the auditService type
type mockauditService struct {
	mock.Mock
}

type mockauditService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauditService) EXPECT() *mockauditService_Expecter {
	return &mockauditService_Expecter{mock: &_m.Mock}
}

// ExportCSV provides a mock function for the type mockauditService
func (_mock *mockauditService) ExportCSV(ctx context.Context, claims *domain.AuthClaims, filter *domain.AuditFilter, w io.Writer) error {
	ret := _mock.Called(ctx, claims, filter, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportCSV")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, *domain.AuditFilter, io.Writer) error); ok {
		r0 = returnFunc(ctx, claims, filter, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockauditService_ExportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportCSV'
type mockauditService_ExportCSV_Call struct {
	*mock.Call
}

// ExportCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - filter *domain.AuditFilter
//   - w io.Writer
func (_e *mockauditService_Expecter) ExportCSV(ctx interface{}, claims interface{}, filter interface{}, w interface{}) *mockauditService_ExportCSV_Call {
	return &mockauditService_ExportCSV_Call{Call: _e.mock.On("ExportCSV", ctx, claims, filter, w)}
}

func (_c *mockauditService_ExportCSV_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, filter *domain.AuditFilter, w io.Writer)) *mockauditService_ExportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 *domain.AuditFilter
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditFilter)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockauditService_ExportCSV_Call) Return(err error) *mockauditService_ExportCSV_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockauditService_ExportCSV_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, filter *domain.AuditFilter, w io.Writer) error) *mockauditService_ExportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// GetByItemID provides a mock function for the type mockauditService
func (_mock *mockauditService) GetByItemID(ctx context.Context, claims *domain.AuthClaims, itemID uuid.UUID) ([]*domain.AuditEntryWithUser, error) {
	ret := _mock.Called(ctx, claims, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetByItemID")
	}

	var r0 []*domain.AuditEntryWithUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, uuid.UUID) ([]*domain.AuditEntryWithUser, error)); ok {
		return returnFunc(ctx, claims, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, uuid.UUID) []*domain.AuditEntryWithUser); ok {
		r0 = returnFunc(ctx, claims, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditEntryWithUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthClaims, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, claims, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauditService_GetByItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByItemID'
type mockauditService_GetByItemID_Call struct {
	*mock.Call
}

// GetByItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - itemID uuid.UUID
func (_e *mockauditService_Expecter) GetByItemID(ctx interface{}, claims interface{}, itemID interface{}) *mockauditService_GetByItemID_Call {
	return &mockauditService_GetByItemID_Call{Call: _e.mock.On("GetByItemID", ctx, claims, itemID)}
}

func (_c *mockauditService_GetByItemID_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, itemID uuid.UUID)) *mockauditService_GetByItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockauditService_GetByItemID_Call) Return(auditEntryWithUsers []*domain.AuditEntryWithUser, err error) *mockauditService_GetByItemID_Call {
	_c.Call.Return(auditEntryWithUsers, err)
	return _c
}

func (_c *mockauditService_GetByItemID_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, itemID uuid.UUID) ([]*domain.AuditEntryWithUser, error)) *mockauditService_GetByItemID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockauditService
func (_mock *mockauditService) List(ctx context.Context, claims *domain.AuthClaims, filter *domain.AuditFilter, page int, pageSize int) (*domain.AuditList, error) {
	ret := _mock.Called(ctx, claims, filter, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.AuditList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, *domain.AuditFilter, int, int) (*domain.AuditList, error)); ok {
		return returnFunc(ctx, claims, filter, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, *domain.AuditFilter, int, int) *domain.AuditList); ok {
		r0 = returnFunc(ctx, claims, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuditList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthClaims, *domain.AuditFilter, int, int) error); ok {
		r1 = returnFunc(ctx, claims, filter, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauditService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockauditService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - filter *domain.AuditFilter
//   - page int
//   - pageSize int
func (_e *mockauditService_Expecter) List(ctx interface{}, claims interface{}, filter interface{}, page interface{}, pageSize interface{}) *mockauditService_List_Call {
	return &mockauditService_List_Call{Call: _e.mock.On("List", ctx, claims, filter, page, pageSize)}
}

func (_c *mockauditService_List_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, filter *domain.AuditFilter, page int, pageSize int)) *mockauditService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 *domain.AuditFilter
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditFilter)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockauditService_List_Call) Return(auditList *domain.AuditList, err error) *mockauditService_List_Call {
	_c.Call.Return(auditList, err)
	return _c
}

func (_c *mockauditService_List_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, filter *domain.AuditFilter, page int, pageSize int) (*domain.AuditList, error)) *mockauditService_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockauthService creates a new instance of mockauthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauthService {
	mock := &mockauthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauthService is an autogenerated mock type for the authService type
type mockauthService struct {
	mock.Mock
}

type mockauthService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauthService) EXPECT() *mockauthService_Expecter {
	return &mockauthService_Expecter{mock: &_m.Mock}
}

// ListUsers provides a mock function for the type mockauthService
func (_mock *mockauthService) ListUsers(ctx context.Context) ([]*domain.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauthService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type mockauthService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockauthService_Expecter) ListUsers(ctx interface{}) *mockauthService_ListUsers_Call {
	return &mockauthService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *mockauthService_ListUsers_Call) Run(run func(ctx context.Context)) *mockauthService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockauthService_ListUsers_Call) Return(users []*domain.User, err error) *mockauthService_ListUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *mockauthService_ListUsers_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.User, error)) *mockauthService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type mockauthService
func (_mock *mockauthService) Login(ctx context.Context, input *domain.LoginInput) (string, *domain.User, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *domain.User
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.LoginInput) (string, *domain.User, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.LoginInput) string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.LoginInput) *domain.User); ok {
		r1 = returnFunc(ctx, input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *domain.LoginInput) error); ok {
		r2 = returnFunc(ctx, input)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockauthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type mockauthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.LoginInput
func (_e *mockauthService_Expecter) Login(ctx interface{}, input interface{}) *mockauthService_Login_Call {
	return &mockauthService_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *mockauthService_Login_Call) Run(run func(ctx context.Context, input *domain.LoginInput)) *mockauthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.LoginInput
		if args[1] != nil {
			arg1 = args[1].(*domain.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockauthService_Login_Call) Return(s string, user *domain.User, err error) *mockauthService_Login_Call {
	_c.Call.Return(s, user, err)
	return _c
}

func (_c *mockauthService_Login_Call) RunAndReturn(run func(ctx context.Context, input *domain.LoginInput) (string, *domain.User, error)) *mockauthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// newMockitemService creates a new instance of mockitemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockitemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockitemService {
	mock := &mockitemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockitemService is an autogenerated mock type for the itemService type
type mockitemService struct {
	mock.Mock
}

type mockitemService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockitemService) EXPECT() *mockitemService_Expecter {
	return &mockitemService_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function for the type mockitemService
func (_mock *mockitemService) CreateItem(ctx context.Context, claims *domain.AuthClaims, input *domain.CreateItemInput) (*domain.Item, error) {
	ret := _mock.Called(ctx, claims, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, *domain.CreateItemInput) (*domain.Item, error)); ok {
		return returnFunc(ctx, claims, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, *domain.CreateItemInput) *domain.Item); ok {
		r0 = returnFunc(ctx, claims, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthClaims, *domain.CreateItemInput) error); ok {
		r1 = returnFunc(ctx, claims, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemService_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type mockitemService_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - input *domain.CreateItemInput
func (_e *mockitemService_Expecter) CreateItem(ctx interface{}, claims interface{}, input interface{}) *mockitemService_CreateItem_Call {
	return &mockitemService_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, claims, input)}
}

func (_c *mockitemService_CreateItem_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, input *domain.CreateItemInput)) *mockitemService_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 *domain.CreateItemInput
		if args[2] != nil {
			arg2 = args[2].(*domain.CreateItemInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockitemService_CreateItem_Call) Return(item *domain.Item, err error) *mockitemService_CreateItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemService_CreateItem_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, input *domain.CreateItemInput) (*domain.Item, error)) *mockitemService_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockitemService
func (_mock *mockitemService) Delete(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID) error {
	ret := _mock.Called(ctx, claims, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, claims, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockitemService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockitemService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - id uuid.UUID
func (_e *mockitemService_Expecter) Delete(ctx interface{}, claims interface{}, id interface{}) *mockitemService_Delete_Call {
	return &mockitemService_Delete_Call{Call: _e.mock.On("Delete", ctx, claims, id)}
}

func (_c *mockitemService_Delete_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID)) *mockitemService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockitemService_Delete_Call) Return(err error) *mockitemService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockitemService_Delete_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID) error) *mockitemService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockitemService
func (_mock *mockitemService) GetByID(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID) (*domain.Item, error) {
	ret := _mock.Called(ctx, claims, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, uuid.UUID) (*domain.Item, error)); ok {
		return returnFunc(ctx, claims, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, uuid.UUID) *domain.Item); ok {
		r0 = returnFunc(ctx, claims, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthClaims, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, claims, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockitemService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - id uuid.UUID
func (_e *mockitemService_Expecter) GetByID(ctx interface{}, claims interface{}, id interface{}) *mockitemService_GetByID_Call {
	return &mockitemService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, claims, id)}
}

func (_c *mockitemService_GetByID_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID)) *mockitemService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockitemService_GetByID_Call) Return(item *domain.Item, err error) *mockitemService_GetByID_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemService_GetByID_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID) (*domain.Item, error)) *mockitemService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function for the type mockitemService
func (_mock *mockitemService) ListItems(ctx context.Context, claims *domain.AuthClaims, filter *domain.ItemFilter, page int, pageSize int) (*domain.ItemList, error) {
	ret := _mock.Called(ctx, claims, filter, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 *domain.ItemList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, *domain.ItemFilter, int, int) (*domain.ItemList, error)); ok {
		return returnFunc(ctx, claims, filter, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, *domain.ItemFilter, int, int) *domain.ItemList); ok {
		r0 = returnFunc(ctx, claims, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ItemList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthClaims, *domain.ItemFilter, int, int) error); ok {
		r1 = returnFunc(ctx, claims, filter, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemService_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type mockitemService_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - filter *domain.ItemFilter
//   - page int
//   - pageSize int
func (_e *mockitemService_Expecter) ListItems(ctx interface{}, claims interface{}, filter interface{}, page interface{}, pageSize interface{}) *mockitemService_ListItems_Call {
	return &mockitemService_ListItems_Call{Call: _e.mock.On("ListItems", ctx, claims, filter, page, pageSize)}
}

func (_c *mockitemService_ListItems_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, filter *domain.ItemFilter, page int, pageSize int)) *mockitemService_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 *domain.ItemFilter
		if args[2] != nil {
			arg2 = args[2].(*domain.ItemFilter)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockitemService_ListItems_Call) Return(itemList *domain.ItemList, err error) *mockitemService_ListItems_Call {
	_c.Call.Return(itemList, err)
	return _c
}

func (_c *mockitemService_ListItems_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, filter *domain.ItemFilter, page int, pageSize int) (*domain.ItemList, error)) *mockitemService_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockitemService
func (_mock *mockitemService) Update(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID, input *domain.UpdateItemInput) (*domain.Item, error) {
	ret := _mock.Called(ctx, claims, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, uuid.UUID, *domain.UpdateItemInput) (*domain.Item, error)); ok {
		return returnFunc(ctx, claims, id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthClaims, uuid.UUID, *domain.UpdateItemInput) *domain.Item); ok {
		r0 = returnFunc(ctx, claims, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthClaims, uuid.UUID, *domain.UpdateItemInput) error); ok {
		r1 = returnFunc(ctx, claims, id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockitemService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *domain.AuthClaims
//   - id uuid.UUID
//   - input *domain.UpdateItemInput
func (_e *mockitemService_Expecter) Update(ctx interface{}, claims interface{}, id interface{}, input interface{}) *mockitemService_Update_Call {
	return &mockitemService_Update_Call{Call: _e.mock.On("Update", ctx, claims, id, input)}
}

func (_c *mockitemService_Update_Call) Run(run func(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID, input *domain.UpdateItemInput)) *mockitemService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthClaims)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *domain.UpdateItemInput
		if args[3] != nil {
			arg3 = args[3].(*domain.UpdateItemInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockitemService_Update_Call) Return(item *domain.Item, err error) *mockitemService_Update_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemService_Update_Call) RunAndReturn(run func(ctx context.Context, claims *domain.AuthClaims, id uuid.UUID, input *domain.UpdateItemInput) (*domain.Item, error)) *mockitemService_Update_Call {
	_c.Call.Return(run)
	return _c
}
