// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware

import (
	"github.com/stpnv0/WarehouseControl/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) Validate(tokenStr string) (*domain.AuthClaims, error) {
	ret := _mock.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *domain.AuthClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.AuthClaims, error)); ok {
		return returnFunc(tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.AuthClaims); ok {
		r0 = returnFunc(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockTokenValidator_Expecter) Validate(tokenStr interface{}) *MockTokenValidator_Validate_Call {
	return &MockTokenValidator_Validate_Call{Call: _e.mock.On("Validate", tokenStr)}
}

func (_c *MockTokenValidator_Validate_Call) Run(run func(tokenStr string)) *MockTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenValidator_Validate_Call) Return(authClaims *domain.AuthClaims, err error) *MockTokenValidator_Validate_Call {
	_c.Call.Return(authClaims, err)
	return _c
}

func (_c *MockTokenValidator_Validate_Call) RunAndReturn(run func(tokenStr string) (*domain.AuthClaims, error)) *MockTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
