// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/stpnv0/WarehouseControl/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockauditRepository creates a new instance of mockauditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauditRepository {
	mock := &mockauditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauditRepository is an autogenerated mock type for the auditRepository type
type mockauditRepository struct {
	mock.Mock
}

type mockauditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauditRepository) EXPECT() *mockauditRepository_Expecter {
	return &mockauditRepository_Expecter{mock: &_m.Mock}
}

// GetByItemID provides a mock function for the type mockauditRepository
func (_mock *mockauditRepository) GetByItemID(ctx context.Context, itemID uuid.UUID) ([]*domain.AuditEntryWithUser, error) {
	ret := _mock.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetByItemID")
	}

	var r0 []*domain.AuditEntryWithUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.AuditEntryWithUser, error)); ok {
		return returnFunc(ctx, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.AuditEntryWithUser); ok {
		r0 = returnFunc(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditEntryWithUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauditRepository_GetByItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByItemID'
type mockauditRepository_GetByItemID_Call struct {
	*mock.Call
}

// GetByItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
func (_e *mockauditRepository_Expecter) GetByItemID(ctx interface{}, itemID interface{}) *mockauditRepository_GetByItemID_Call {
	return &mockauditRepository_GetByItemID_Call{Call: _e.mock.On("GetByItemID", ctx, itemID)}
}

func (_c *mockauditRepository_GetByItemID_Call) Run(run func(ctx context.Context, itemID uuid.UUID)) *mockauditRepository_GetByItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockauditRepository_GetByItemID_Call) Return(auditEntryWithUsers []*domain.AuditEntryWithUser, err error) *mockauditRepository_GetByItemID_Call {
	_c.Call.Return(auditEntryWithUsers, err)
	return _c
}

func (_c *mockauditRepository_GetByItemID_Call) RunAndReturn(run func(ctx context.Context, itemID uuid.UUID) ([]*domain.AuditEntryWithUser, error)) *mockauditRepository_GetByItemID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockauditRepository
func (_mock *mockauditRepository) List(ctx context.Context, filter *domain.AuditFilter, limit int, offset int) ([]*domain.AuditEntryWithUser, int64, error) {
	ret := _mock.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.AuditEntryWithUser
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditFilter, int, int) ([]*domain.AuditEntryWithUser, int64, error)); ok {
		return returnFunc(ctx, filter, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditFilter, int, int) []*domain.AuditEntryWithUser); ok {
		r0 = returnFunc(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditEntryWithUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditFilter, int, int) int64); ok {
		r1 = returnFunc(ctx, filter, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *domain.AuditFilter, int, int) error); ok {
		r2 = returnFunc(ctx, filter, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockauditRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockauditRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.AuditFilter
//   - limit int
//   - offset int
func (_e *mockauditRepository_Expecter) List(ctx interface{}, filter interface{}, limit interface{}, offset interface{}) *mockauditRepository_List_Call {
	return &mockauditRepository_List_Call{Call: _e.mock.On("List", ctx, filter, limit, offset)}
}

func (_c *mockauditRepository_List_Call) Run(run func(ctx context.Context, filter *domain.AuditFilter, limit int, offset int)) *mockauditRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditFilter
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditFilter)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockauditRepository_List_Call) Return(auditEntryWithUsers []*domain.AuditEntryWithUser, n int64, err error) *mockauditRepository_List_Call {
	_c.Call.Return(auditEntryWithUsers, n, err)
	return _c
}

func (_c *mockauditRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter *domain.AuditFilter, limit int, offset int) ([]*domain.AuditEntryWithUser, int64, error)) *mockauditRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockuserRepository creates a new instance of mockuserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserRepository {
	mock := &mockuserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserRepository is an autogenerated mock type for the userRepository type
type mockuserRepository struct {
	mock.Mock
}

type mockuserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserRepository) EXPECT() *mockuserRepository_Expecter {
	return &mockuserRepository_Expecter{mock: &_m.Mock}
}

// GetByUsername provides a mock function for the type mockuserRepository
func (_mock *mockuserRepository) GetByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type mockuserRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockuserRepository_Expecter) GetByUsername(ctx interface{}, username interface{}) *mockuserRepository_GetByUsername_Call {
	return &mockuserRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *mockuserRepository_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *mockuserRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserRepository_GetByUsername_Call) Return(user *domain.User, err error) *mockuserRepository_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserRepository_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *mockuserRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockuserRepository
func (_mock *mockuserRepository) List(ctx context.Context) ([]*domain.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockuserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockuserRepository_Expecter) List(ctx interface{}) *mockuserRepository_List_Call {
	return &mockuserRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *mockuserRepository_List_Call) Run(run func(ctx context.Context)) *mockuserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockuserRepository_List_Call) Return(users []*domain.User, err error) *mockuserRepository_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *mockuserRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.User, error)) *mockuserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// GenerateJWT provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GenerateJWT(user *domain.User) (string, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) (string, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.User) string); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_GenerateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateJWT'
type MockTokenManager_GenerateJWT_Call struct {
	*mock.Call
}

// GenerateJWT is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockTokenManager_Expecter) GenerateJWT(user interface{}) *MockTokenManager_GenerateJWT_Call {
	return &MockTokenManager_GenerateJWT_Call{Call: _e.mock.On("GenerateJWT", user)}
}

func (_c *MockTokenManager_GenerateJWT_Call) Run(run func(user *domain.User)) *MockTokenManager_GenerateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_GenerateJWT_Call) Return(s string, err error) *MockTokenManager_GenerateJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenManager_GenerateJWT_Call) RunAndReturn(run func(user *domain.User) (string, error)) *MockTokenManager_GenerateJWT_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) Validate(tokenStr string) (*domain.AuthClaims, error) {
	ret := _mock.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *domain.AuthClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.AuthClaims, error)); ok {
		return returnFunc(tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.AuthClaims); ok {
		r0 = returnFunc(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenManager_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockTokenManager_Expecter) Validate(tokenStr interface{}) *MockTokenManager_Validate_Call {
	return &MockTokenManager_Validate_Call{Call: _e.mock.On("Validate", tokenStr)}
}

func (_c *MockTokenManager_Validate_Call) Run(run func(tokenStr string)) *MockTokenManager_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_Validate_Call) Return(authClaims *domain.AuthClaims, err error) *MockTokenManager_Validate_Call {
	_c.Call.Return(authClaims, err)
	return _c
}

func (_c *MockTokenManager_Validate_Call) RunAndReturn(run func(tokenStr string) (*domain.AuthClaims, error)) *MockTokenManager_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockitemRepository creates a new instance of mockitemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockitemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockitemRepository {
	mock := &mockitemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockitemRepository is an autogenerated mock type for the itemRepository type
type mockitemRepository struct {
	mock.Mock
}

type mockitemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockitemRepository) EXPECT() *mockitemRepository_Expecter {
	return &mockitemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) Create(ctx context.Context, userID uuid.UUID, input *domain.CreateItemInput) (*domain.Item, error) {
	ret := _mock.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.CreateItemInput) (*domain.Item, error)); ok {
		return returnFunc(ctx, userID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.CreateItemInput) *domain.Item); ok {
		r0 = returnFunc(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.CreateItemInput) error); ok {
		r1 = returnFunc(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockitemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input *domain.CreateItemInput
func (_e *mockitemRepository_Expecter) Create(ctx interface{}, userID interface{}, input interface{}) *mockitemRepository_Create_Call {
	return &mockitemRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, input)}
}

func (_c *mockitemRepository_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, input *domain.CreateItemInput)) *mockitemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.CreateItemInput
		if args[2] != nil {
			arg2 = args[2].(*domain.CreateItemInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockitemRepository_Create_Call) Return(item *domain.Item, err error) *mockitemRepository_Create_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, input *domain.CreateItemInput) (*domain.Item, error)) *mockitemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) Delete(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockitemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockitemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *mockitemRepository_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *mockitemRepository_Delete_Call {
	return &mockitemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *mockitemRepository_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *mockitemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockitemRepository_Delete_Call) Return(err error) *mockitemRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockitemRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *mockitemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockitemRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *mockitemRepository_Expecter) GetByID(ctx interface{}, id interface{}) *mockitemRepository_GetByID_Call {
	return &mockitemRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockitemRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *mockitemRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemRepository_GetByID_Call) Return(item *domain.Item, err error) *mockitemRepository_GetByID_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Item, error)) *mockitemRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) List(ctx context.Context, filter *domain.ItemFilter, limit int, offset int) ([]*domain.Item, int64, error) {
	ret := _mock.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Item
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ItemFilter, int, int) ([]*domain.Item, int64, error)); ok {
		return returnFunc(ctx, filter, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ItemFilter, int, int) []*domain.Item); ok {
		r0 = returnFunc(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ItemFilter, int, int) int64); ok {
		r1 = returnFunc(ctx, filter, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *domain.ItemFilter, int, int) error); ok {
		r2 = returnFunc(ctx, filter, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockitemRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockitemRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.ItemFilter
//   - limit int
//   - offset int
func (_e *mockitemRepository_Expecter) List(ctx interface{}, filter interface{}, limit interface{}, offset interface{}) *mockitemRepository_List_Call {
	return &mockitemRepository_List_Call{Call: _e.mock.On("List", ctx, filter, limit, offset)}
}

func (_c *mockitemRepository_List_Call) Run(run func(ctx context.Context, filter *domain.ItemFilter, limit int, offset int)) *mockitemRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ItemFilter
		if args[1] != nil {
			arg1 = args[1].(*domain.ItemFilter)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockitemRepository_List_Call) Return(items []*domain.Item, n int64, err error) *mockitemRepository_List_Call {
	_c.Call.Return(items, n, err)
	return _c
}

func (_c *mockitemRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter *domain.ItemFilter, limit int, offset int) ([]*domain.Item, int64, error)) *mockitemRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) Update(ctx context.Context, userID uuid.UUID, id uuid.UUID, input *domain.UpdateItemInput) (*domain.Item, error) {
	ret := _mock.Called(ctx, userID, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *domain.UpdateItemInput) (*domain.Item, error)); ok {
		return returnFunc(ctx, userID, id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *domain.UpdateItemInput) *domain.Item); ok {
		r0 = returnFunc(ctx, userID, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *domain.UpdateItemInput) error); ok {
		r1 = returnFunc(ctx, userID, id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockitemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - input *domain.UpdateItemInput
func (_e *mockitemRepository_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, input interface{}) *mockitemRepository_Update_Call {
	return &mockitemRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, input)}
}

func (_c *mockitemRepository_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, input *domain.UpdateItemInput)) *mockitemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *domain.UpdateItemInput
		if args[3] != nil {
			arg3 = args[3].(*domain.UpdateItemInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockitemRepository_Update_Call) Return(item *domain.Item, err error) *mockitemRepository_Update_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemRepository_Update_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, input *domain.UpdateItemInput) (*domain.Item, error)) *mockitemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
